services:
  client:
    build:
      context: ./client
    container_name: client
    ports:
      - "3001:80"
    networks:
      appnet:
        ipv4_address: ${CLIENT_IP}

  server:
    build:
      context: ./backend
    container_name: server
    ports:
      - "5001:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    networks:
      appnet:
        ipv4_address: ${SERVER_IP}

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      appnet:
        ipv4_address: ${REDIS_IP}

networks:
  appnet:
    driver: bridge
    ipam:
      config:
        - subnet: ${APP_SUBNET}
          ip_range: ${APP_IP_RANGE}
          gateway: ${APP_GATEWAY}