---
- name: Install git
  apt:
    name: git
    state: present
    update_cache: true
  become: true
  tags: [git, install]

- name: Remove existing application directory
  file:
    path: "{{ app_directory }}"
    state: absent
  tags: [git, clone]

- name: Clone application repository
  git:
    repo: "{{ repo_url }}"
    dest: "{{ app_directory }}"
    version: "{{ repo_branch }}"
    force: true
  tags: [git, clone]

- name: Set ownership of application directory
  file:
    path: "{{ app_directory }}"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    recurse: true
  become: true
  tags: [git, clone]
