---
- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true
  become: true
  tags: [docker, install]

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true
  tags: [docker, install]

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  become: true
  tags: [docker, install]

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true
  become: true
  tags: [docker, install]

- name: Add user to docker group
  user:
    name: "{{ app_user }}"
    groups: docker
    append: true
  become: true
  tags: [docker, configure]

- name: Install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: "0755"
  become: true
  tags: [docker, install]

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: true
  become: true
  tags: [docker, configure]

- name: Pull required Docker images
  docker_image:
    name: "{{ item }}"
    source: pull
  loop:
    - "node:18-alpine"
    - "nginx:alpine"
    - "mongo:7.0"
    - "redis:alpine"
  tags: [docker, images]
