---
- name: Create root .env file for docker-compose
  copy:
    content: |
      CLIENT_IP={{ client_ip }}
      SERVER_IP={{ server_ip }}
      MONGO_IP={{ mongo_ip }}
      REDIS_IP={{ redis_ip }}
      APP_SUBNET={{ docker_subnet }}
      APP_IP_RANGE={{ docker_ip_range }}
      APP_GATEWAY={{ docker_gateway }}
    dest: "{{ app_directory }}/.env"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0644'
  tags: [environment, setup]

- name: Create backend .env file
  copy:
    content: |
      MONGODB_URI={{ mongodb_uri }}
      PORT=5000
    dest: "{{ app_directory }}/backend/.env"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0600'
  tags: [environment, setup]